'use client'
import React, { useState } from 'react'
import { CldImage, CldUploadButton, CldUploadWidgetResults } from 'next-cloudinary'

interface CldUploadButtonType extends CldUploadWidgetResults {
  info: {
    public_id: string
  }
}



function page() {
  const [image, setImage] = useState<string>("jrdzb1bqwzbf1sxh758v")

  return (
    <main className='container mx-auto flex flex-col items-center justify-center h-d'>
      <div>

        <CldUploadButton onUpload={(results:any, widget: any) =>  {
          console.log(results.info.public_id);
          setImage(results.info.public_id)
          widget.close();
        }} className='btn btn-primary' uploadPreset="bubchj8t" />
 
        <CldImage
          width="960"
          height="600"
          src={image}
          sizes="100vw"
          alt="Description of my image"
          />
        d,lkm 


<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi laboriosam aliquid molestias sequi odit porro voluptate culpa sunt asperiores corporis tenetur ullam enim nostrum error dolor, dolorum animi omnis amet beatae! Nemo unde dignissimos sunt. Quod nesciunt dolor officiis ratione expedita incidunt voluptatum sapiente optio voluptate ab quaerat ipsum labore inventore reprehenderit, sed ducimus. Debitis dolores quaerat expedita illo natus animi voluptas repellendus eaque excepturi. Quas eaque molestias, voluptatem alias recusandae numquam ullam hic at neque, id, debitis incidunt impedit quibusdam sint ratione atque deleniti ab fugit soluta rerum! Voluptatum cupiditate illum similique deserunt totam, quod tempore fuga! Recusandae voluptas quisquam dolore, sit dolorem eius perspiciatis officiis facere assumenda delectus doloribus explicabo, repellat qui error voluptatibus impedit alias quas! Excepturi enim maiores ipsa, accusantium, a molestiae nobis velit illo perspiciatis dolorum cupiditate voluptatum blanditiis quaerat aspernatur? Earum, asperiores inventore deleniti ex labore optio saepe rerum et minus doloremque, qui vel ut expedita sed quibusdam blanditiis. Placeat culpa iusto quod minus aliquam quaerat harum soluta velit, repellat ratione repellendus, est cupiditate quos tempore autem excepturi sunt perferendis officiis laudantium fuga? Nisi alias quidem perferendis quia, iusto minus hic provident nostrum iure amet, dignissimos ad nihil deserunt molestiae, velit fugiat optio ipsum!</p>
      </div>
    </main>
  )
}

export default page